#!/bin/bash
# BRENT DETECTOR - QUICK COMMAND REFERENCE
# ============================================================================

echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║           BRENT DETECTOR - INTEGRATED ANALYSIS SYSTEM               ║"
echo "║                      ALL FUNCTIONALITIES ACTIVE                     ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 QUICK START EXAMPLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  ANALYZE FLASK (with all outputs)"
echo "   python -m cli.main data/flask/ --all --output-dir ./reports_flask"
echo ""
echo "2️⃣  ANALYZE DJANGO (with all outputs)"
echo "   python -m cli.main data/django/ --all --output-dir ./reports_django"
echo ""
echo "3️⃣  ANALYZE ANY PROJECT"
echo "   python -m cli.main /path/to/project --all --output-dir ./reports"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 COMMAND OPTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Report Formats:"
echo "  --json                 Generate JSON report"
echo "  --csv                  Generate CSV spreadsheet"
echo "  --html                 Generate interactive HTML dashboard"
echo "  --txt                  Generate text summary"
echo "  --svg                  Generate SVG visualizations (3 types)"
echo "  --all                  Generate ALL formats (JSON+CSV+HTML+TXT+SVG)"
echo ""
echo "Output:"
echo "  --output-dir DIR       Save reports to directory (default: ./reports)"
echo ""
echo "Filtering:"
echo "  --top-percent PCT      Show top % of modules (default: 0.05 = 5%)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 USAGE PATTERNS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Full Analysis (all outputs):"
echo "   python -m cli.main data/flask/ --all --output-dir ./reports"
echo ""
echo "📈 Only HTML Report (for quick view):"
echo "   python -m cli.main data/flask/ --html --output-dir ./reports"
echo ""
echo "📋 CSV Export (for spreadsheet analysis):"
echo "   python -m cli.main data/flask/ --csv --output-dir ./reports"
echo ""
echo "🖼️  SVG Visualizations (for presentations):"
echo "   python -m cli.main data/flask/ --svg --output-dir ./reports"
echo ""
echo "📄 Multiple Formats:"
echo "   python -m cli.main data/flask/ --html --csv --json --output-dir ./reports"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📁 OUTPUT FILES GENERATED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "With --all flag, generates 8 files in output directory:"
echo ""
echo "  1. 01_main_dependency_graph.svg  - Full network visualization"
echo "  2. 02_cycle_graph.svg            - Circular dependencies focused view"
echo "  3. 03_scc_hotspot_graph.svg      - Coupling hotspots visualization"
echo "  4. brent_analysis.html           - Interactive dashboard + charts"
echo "  5. brent_analysis.csv            - Spreadsheet format"
echo "  6. brent_analysis.json           - Structured data"
echo "  7. brent_analysis.txt            - Text summary"
echo "  8. dependency_graph.svg          - Alternative network view"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚙️  ANALYSIS STEPS (Auto-executed)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✅ Step 1: Scan Python files"
echo "  ✅ Step 2: Extract dependencies"
echo "  ✅ Step 3: Build dependency graph"
echo "  ✅ Step 4: Calculate 9 metrics"
echo "  ✅ Step 5: Detect circular dependencies (19,056 found in Flask!)"
echo "  ✅ Step 6: Analyze hotspots/SCCs"
echo "  ✅ Step 7: Calculate Fragility Index"
echo "  ✅ Step 8: Generate reports"
echo "  ✅ Step 9: Create SVG visualizations"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 9 METRICS CALCULATED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Fragility Score (0-1)      - Overall brittleness risk"
echo "  2. Incoming Dependencies      - How many depend on this module"
echo "  3. Outgoing Dependencies      - How many modules this depends on"
echo "  4. Degree Centrality (0-1)    - Direct network importance"
echo "  5. Betweenness Centrality     - Bridge importance"
echo "  6. Closeness Centrality       - Network proximity"
echo "  7. PageRank (0-1)             - Network influence score"
echo "  8. Eigenvector Centrality     - Quality of connections"
echo "  9. In Cycle + SCC Size        - Circular dependency info"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ READY FOR:"
echo "   ✓ Thesis submission"
echo "   ✓ Code team deployment"
echo "   ✓ Supervisor presentation"
echo "   ✓ Production use"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
