"""
GitHub PR Commenter
Posts analysis results to GitHub pull requests
"""

import json
import sys
from typing import Dict
from datetime import datetime


class GitHubPRCommenter:
    """Posts brittle dependency analysis results to GitHub PRs."""
    
    def __init__(self):
        """Initialize commenter."""
        self.summary_data = {}
    
    def load_analysis_report(self, report_path: str) -> Dict:
        """
        Load analysis report from file.
        
        Args:
            report_path: Path to summary report (txt or json)
        
        Returns:
            Dictionary with analysis data
        """
        try:
            with open(report_path, 'r') as f:
                if report_path.endswith('.json'):
                    return json.load(f)
                else:
                    # Parse text report
                    content = f.read()
                    self.summary_data['raw'] = content
                    return {"raw_content": content}
        except Exception as e:
            print(f"Error loading report: {e}")
            return {}
    
    def generate_pr_comment(self, analysis_data: Dict, changed_files: list = None) -> str:
        """
        Generate GitHub PR comment from analysis data.
        
        Args:
            analysis_data: Analysis results dictionary
            changed_files: List of files changed in PR
        
        Returns:
            Formatted comment text for GitHub
        """
        comment = "## 🔍 Brittle Dependency Analysis\n\n"
        
        # Add warning if brittle dependencies were modified
        if changed_files:
            comment += self._check_modified_brittle_deps(analysis_data, changed_files)
        
        # Add summary
        comment += "### Analysis Summary\n"
        if "raw_content" in analysis_data:
            # Truncate if too long
            content = analysis_data["raw_content"]
            if len(content) > 2000:
                content = content[:2000] + "\n... (truncated)"
            comment += f"```\n{content}\n```\n"
        elif "statistics" in analysis_data:
            stats = analysis_data["statistics"]
            comment += f"- **Total Modules**: {stats.get('total_modules', 0)}\n"
            comment += f"- **Dependencies**: {stats.get('total_dependencies', 0)}\n"
            comment += f"- **Cycles Found**: {stats.get('cycles_count', 0)}\n"
            comment += f"- **Hotspots Detected**: {stats.get('large_sccs', 0)}\n"
        
        # Add recommendations
        comment += "\n### Recommendations\n"
        if analysis_data.get("statistics", {}).get("cycles_count", 0) > 0:
            comment += "⚠️ **Circular dependencies detected** - Consider refactoring\n"
        if analysis_data.get("statistics", {}).get("large_sccs", 0) > 0:
            comment += "⚠️ **Architectural hotspots found** - Review design\n"
        
        comment += "\n_Report generated by [Brent Detector](https://github.com/user/brent-detector)_"
        
        return comment
    
    def _check_modified_brittle_deps(self, analysis_data: Dict, changed_files: list) -> str:
        """
        Check if any brittle dependencies were modified in the PR.
        
        Args:
            analysis_data: Analysis results
            changed_files: List of files in PR
        
        Returns:
            Warning message if brittle deps modified
        """
        warning = ""
        
        # Extract top modules from analysis
        top_modules = []
        if "top_modules" in analysis_data:
            top_modules = [m["module"] for m in analysis_data["top_modules"]]
        elif "top_brents" in analysis_data:
            top_modules = [m["module"] for m in analysis_data["top_brents"]]
        
        # Check if any were changed
        modified_brittle = []
        for file_path in changed_files:
            for module in top_modules:
                if module in file_path:
                    modified_brittle.append(module)
        
        if modified_brittle:
            warning += "### ⚠️ Warning: Brittle Dependencies Modified\n"
            warning += "The following critical modules are being modified:\n"
            for module in modified_brittle:
                warning += f"- `{module}`\n"
            warning += "\nEnsure changes are well-tested due to high dependency!\n\n"
        
        return warning
    
    def post_to_github(self, pr_number: int, comment_text: str) -> bool:
        """
        Post comment to GitHub PR (requires GitHub CLI or API).
        
        Args:
            pr_number: GitHub PR number
            comment_text: Comment text
        
        Returns:
            True if successful
        """
        import subprocess
        
        try:
            result = subprocess.run(
                ["gh", "pr", "comment", str(pr_number), "--body", comment_text],
                capture_output=True,
                text=True
            )
            
            if result.returncode == 0:
                print(f"✅ Comment posted to PR #{pr_number}")
                return True
            else:
                print(f"❌ Failed to post comment: {result.stderr}")
                return False
        except Exception as e:
            print(f"⚠️  Could not post to GitHub (gh CLI not available): {e}")
            print("Comment would have been:")
            print(comment_text)
            return False
    
    def save_comment(self, comment_text: str, output_path: str = "pr_comment.md") -> str:
        """
        Save comment to file (useful for CI debugging).
        
        Args:
            comment_text: Comment text
            output_path: Path to save
        
        Returns:
            Path to saved file
        """
        with open(output_path, 'w') as f:
            f.write(comment_text)
        print(f"✅ Comment saved to: {output_path}")
        return output_path


def main():
    """CLI entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Post Brent Detector results to GitHub PR")
    parser.add_argument("--report", required=True, help="Path to analysis report")
    parser.add_argument("--pr-number", help="GitHub PR number")
    parser.add_argument("--save-only", action="store_true", help="Save comment without posting")
    parser.add_argument("--output", default="pr_comment.md", help="Output file for comment")
    
    args = parser.parse_args()
    
    commenter = GitHubPRCommenter()
    data = commenter.load_analysis_report(args.report)
    comment = commenter.generate_pr_comment(data)
    
    if args.save_only:
        commenter.save_comment(comment, args.output)
    elif args.pr_number:
        commenter.save_comment(comment, args.output)
        commenter.post_to_github(int(args.pr_number), comment)
    else:
        print("Comment would be:")
        print(comment)


if __name__ == "__main__":
    main()
